-- Daily horoscope (rashifal). One row per sign per day, generated by the
-- nightly cron (deploy/cron-horoscope.sh → /api/cron/horoscope) and
-- auto-pushed to WordPress (one post per sign) as soon as it is generated.
CREATE TABLE IF NOT EXISTS horoscopes (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  for_date         date NOT NULL,               -- the day this forecast is FOR (IST)
  sign             text NOT NULL,               -- canonical key: mesh, vrishabh, ...
  forecast         text NOT NULL,               -- today's forecast (Hindi)
  shubh_rang       text NOT NULL,               -- lucky colour name
  shubh_ank        text NOT NULL,               -- lucky number(s)
  shubh_samay      text NOT NULL,               -- lucky time window
  zodiac_content   text DEFAULT '',             -- sign-specific guidance
  lucky_color_code text DEFAULT '',             -- hex for the lucky colour
  mood             text DEFAULT '',
  solution         text DEFAULT '',             -- upaay / remedy
  wp_status        text NOT NULL DEFAULT 'pending',  -- pending | pushed | failed | skipped
  wp_post_id       text,                        -- id/link returned by WordPress
  wp_error         text,
  created_at       timestamptz DEFAULT now(),
  updated_at       timestamptz DEFAULT now(),
  UNIQUE (for_date, sign)
);
CREATE INDEX IF NOT EXISTS horoscopes_for_date_idx ON horoscopes (for_date DESC);

-- Upgrade a table created by an earlier version of this migration.
ALTER TABLE horoscopes ADD COLUMN IF NOT EXISTS zodiac_content   text DEFAULT '';
ALTER TABLE horoscopes ADD COLUMN IF NOT EXISTS lucky_color_code text DEFAULT '';
ALTER TABLE horoscopes ADD COLUMN IF NOT EXISTS mood             text DEFAULT '';
ALTER TABLE horoscopes ADD COLUMN IF NOT EXISTS solution         text DEFAULT '';
