-- ═══════════════════════════════════════════════════════════════
-- Category feeds — each beat gets its own set of sources (RSS + sitemap),
-- Indian (EN + HI) and international. The full category is stored in `desk`
-- (national/world/politics/business/sports/enter/tech); `focus` holds the
-- constraint-safe value used by the admin /sources grouping.
--
-- The clusterer reads sources.desk as a strong category hint
-- (lib/clustering/lexical.ts FOCUS_TO_CATEGORY) so a story from a Sports
-- feed lands in Sports even when the headline is ambiguous.
--
-- All URLs were verified live (200 + valid RSS/Atom) before inclusion.
-- ═══════════════════════════════════════════════════════════════

insert into public.sources (name, source_type, url, language, desk, focus, is_active) values
  ('The Hindu · National', 'rss', 'https://www.thehindu.com/news/national/feeder/default.rss', 'en', 'national', 'general', true),
  ('TOI · India', 'rss', 'https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms', 'en', 'national', 'general', true),
  ('Hindustan Times · India', 'rss', 'https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml', 'en', 'national', 'general', true),
  ('India Today · India', 'rss', 'https://www.indiatoday.in/rss/1206578', 'en', 'national', 'general', true),
  ('DNA · India', 'rss', 'https://www.dnaindia.com/feeds/india.xml', 'en', 'national', 'general', true),
  ('Indian Express · India', 'rss', 'https://indianexpress.com/section/india/feed/', 'en', 'national', 'general', true),
  ('Aaj Tak · News', 'rss', 'https://www.aajtak.in/rssfeeds/?id=home', 'hi', 'national', 'general', true),
  ('Amar Ujala · India', 'rss', 'https://www.amarujala.com/rss/india-news.xml', 'hi', 'national', 'general', true),
  ('Dainik Bhaskar · National', 'rss', 'https://www.bhaskar.com/rss-v1--category-1061.xml', 'hi', 'national', 'general', true),
  ('The Hindu · International', 'rss', 'https://www.thehindu.com/news/international/feeder/default.rss', 'en', 'world', 'general', true),
  ('Hindustan Times · World', 'rss', 'https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml', 'en', 'world', 'general', true),
  ('TOI · World', 'rss', 'https://timesofindia.indiatimes.com/rssfeeds/296589292.cms', 'en', 'world', 'general', true),
  ('Indian Express · World', 'rss', 'https://indianexpress.com/section/world/feed/', 'en', 'world', 'general', true),
  ('NDTV · India', 'rss', 'https://feeds.feedburner.com/ndtvnews-india-news', 'en', 'national', 'general', true),
  ('The Guardian · World', 'rss', 'https://www.theguardian.com/world/rss', 'en', 'world', 'general', true),
  ('NYT · World', 'rss', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', 'en', 'world', 'general', true),
  ('Al Jazeera · All', 'rss', 'https://www.aljazeera.com/xml/rss/all.xml', 'en', 'world', 'general', true),
  ('DW · All', 'rss', 'https://rss.dw.com/rdf/rss-en-all', 'en', 'world', 'general', true),
  ('NDTV · World', 'rss', 'https://feeds.feedburner.com/ndtvnews-world-news', 'en', 'world', 'general', true),
  ('France24 · World', 'rss', 'https://www.france24.com/en/rss', 'en', 'world', 'general', true),
  ('Indian Express · Politics', 'rss', 'https://indianexpress.com/section/political-pulse/feed/', 'en', 'politics', 'general', true),
  ('BBC · World', 'rss', 'https://feeds.bbci.co.uk/news/world/rss.xml', 'en', 'world', 'general', true),
  ('TOI · Business', 'rss', 'https://timesofindia.indiatimes.com/rssfeeds/1898055.cms', 'en', 'business', 'business', true),
  ('The Hindu · Business', 'rss', 'https://www.thehindu.com/business/feeder/default.rss', 'en', 'business', 'business', true),
  ('The Guardian · US Politics', 'rss', 'https://www.theguardian.com/us-news/us-politics/rss', 'en', 'politics', 'general', true),
  ('Hindustan Times · Business', 'rss', 'https://www.hindustantimes.com/feeds/rss/business/rssfeed.xml', 'en', 'business', 'business', true),
  ('Indian Express · Business', 'rss', 'https://indianexpress.com/section/business/feed/', 'en', 'business', 'business', true),
  ('News18 · India', 'rss', 'https://www.news18.com/rss/india.xml', 'en', 'national', 'general', true),
  ('Moneycontrol · Top', 'rss', 'https://www.moneycontrol.com/rss/MCtopnews.xml', 'en', 'business', 'business', true),
  ('Business Standard · Markets', 'rss', 'https://www.business-standard.com/rss/markets-106.rss', 'en', 'business', 'business', true),
  ('CNN · World', 'rss', 'http://rss.cnn.com/rss/edition_world.rss', 'en', 'world', 'general', true),
  ('Livemint · Top', 'rss', 'https://www.livemint.com/rss/news', 'en', 'business', 'business', true),
  ('BBC · Business', 'rss', 'https://feeds.bbci.co.uk/news/business/rss.xml', 'en', 'business', 'business', true),
  ('NYT · Business', 'rss', 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml', 'en', 'business', 'business', true),
  ('Moneycontrol · Markets', 'rss', 'https://www.moneycontrol.com/rss/marketreports.xml', 'en', 'business', 'business', true),
  ('TOI · Sports', 'rss', 'https://timesofindia.indiatimes.com/rssfeeds/4719148.cms', 'en', 'sports', 'sports', true),
  ('NDTV Profit', 'rss', 'https://feeds.feedburner.com/ndtvprofit-latest', 'en', 'business', 'business', true),
  ('The Hindu · Sport', 'rss', 'https://www.thehindu.com/sport/feeder/default.rss', 'en', 'sports', 'sports', true),
  ('Hindustan Times · Sports', 'rss', 'https://www.hindustantimes.com/feeds/rss/sports/rssfeed.xml', 'en', 'sports', 'sports', true),
  ('Zee News Hindi · India', 'rss', 'https://zeenews.india.com/hindi/india.xml', 'hi', 'national', 'general', true),
  ('Indian Express · Sports', 'rss', 'https://indianexpress.com/section/sports/feed/', 'en', 'sports', 'sports', true),
  ('ESPNcricinfo', 'rss', 'https://www.espncricinfo.com/rss/content/story/feeds/0.xml', 'en', 'sports', 'sports', true),
  ('BBC · Sport', 'rss', 'https://feeds.bbci.co.uk/sport/rss.xml', 'en', 'sports', 'sports', true),
  ('The Guardian · Sport', 'rss', 'https://www.theguardian.com/sport/rss', 'en', 'sports', 'sports', true),
  ('TOI · Entertainment', 'rss', 'https://timesofindia.indiatimes.com/rssfeeds/1081479906.cms', 'en', 'enter', 'entertainment', true),
  ('The Hindu · Entertainment', 'rss', 'https://www.thehindu.com/entertainment/feeder/default.rss', 'en', 'enter', 'entertainment', true),
  ('Hindustan Times · Entertainment', 'rss', 'https://www.hindustantimes.com/feeds/rss/entertainment/rssfeed.xml', 'en', 'enter', 'entertainment', true),
  ('NDTV · Politics', 'rss', 'https://feeds.feedburner.com/NDTV-LatestNews', 'en', 'politics', 'general', true),
  ('Indian Express · Entertainment', 'rss', 'https://indianexpress.com/section/entertainment/feed/', 'en', 'enter', 'entertainment', true),
  ('Pinkvilla', 'rss', 'https://www.pinkvilla.com/rss.xml', 'en', 'enter', 'entertainment', true),
  ('Sky Sports · Top', 'rss', 'https://www.skysports.com/rss/12040', 'en', 'sports', 'sports', true),
  ('ThePrint · Politics', 'rss', 'https://theprint.in/category/politics/feed/', 'en', 'politics', 'general', true),
  ('The Hindu · Sci-Tech', 'rss', 'https://www.thehindu.com/sci-tech/feeder/default.rss', 'en', 'tech', 'tech', true),
  ('TOI · Tech', 'rss', 'https://timesofindia.indiatimes.com/rssfeeds/66949542.cms', 'en', 'tech', 'tech', true),
  ('NDTV · Movies', 'rss', 'https://feeds.feedburner.com/ndtvmovies-latest', 'en', 'enter', 'entertainment', true),
  ('Indian Express · Tech', 'rss', 'https://indianexpress.com/section/technology/feed/', 'en', 'tech', 'tech', true),
  ('Hindustan Times · Tech', 'rss', 'https://www.hindustantimes.com/feeds/rss/technology/rssfeed.xml', 'en', 'tech', 'tech', true),
  ('The Verge', 'rss', 'https://www.theverge.com/rss/index.xml', 'en', 'tech', 'tech', true),
  ('Variety', 'rss', 'https://variety.com/feed/', 'en', 'enter', 'entertainment', true),
  ('BBC · Technology', 'rss', 'https://feeds.bbci.co.uk/news/technology/rss.xml', 'en', 'tech', 'tech', true),
  ('Ars Technica', 'rss', 'https://feeds.arstechnica.com/arstechnica/index', 'en', 'tech', 'tech', true),
  ('Bollywood Hungama', 'rss', 'https://www.bollywoodhungama.com/rss/news.xml', 'en', 'enter', 'entertainment', true),
  ('The Guardian · Film', 'rss', 'https://www.theguardian.com/film/rss', 'en', 'enter', 'entertainment', true),
  ('Gadgets360', 'rss', 'https://feeds.feedburner.com/gadgets360-latest', 'en', 'tech', 'tech', true),
  ('TOI · Cricket', 'rss', 'https://timesofindia.indiatimes.com/rssfeeds/54829575.cms', 'en', 'sports', 'sports', true),
  ('NDTV · Cricket', 'rss', 'https://feeds.feedburner.com/ndtvsports-cricket', 'en', 'sports', 'sports', true),
  ('The Guardian · Technology', 'rss', 'https://www.theguardian.com/technology/rss', 'en', 'tech', 'tech', true),
  ('Engadget', 'rss', 'https://www.engadget.com/rss.xml', 'en', 'tech', 'tech', true),
  ('TechCrunch', 'rss', 'https://techcrunch.com/feed/', 'en', 'tech', 'tech', true),
  ('NYT · Technology', 'rss', 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml', 'en', 'tech', 'tech', true),
  ('CNBC · Top', 'rss', 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114', 'en', 'business', 'business', true)
on conflict (url) do nothing;
